food_plan/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plan.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path(r'__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

plan/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views


app_name = "plan"

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/profile/', views.lk, name='lk'),
    path('register/', views.register, name='register'),
    path('recipe/<int:pk>/', views.recipe_detail, name='recipe_detail'),
    path('card3/', views.card3, name='card3'),
    path('order/', views.order, name='order'),
    path('free-recipe/', views.view_random_recipe, name='view_random_recipe'),
    ]

templates/auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
    <title>Foodplan 2021 - Меню на неделю FOODPLAN</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse1"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse1">
                    <ul class="navbar-nav w-100">
                        
                        <li class="nav-item align-items-center d-md-flex flex-grow-1 justify-content-end">
                            <button class="btn btn-outline-success me-2 shadow-none foodplan_green foodplan__border_green">Подписка</button>
                            <button class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <div class="card p-3 mb-5 foodplan__shadow">
                    <a href="#" class="link-secondary fw-light foodplan__backButton">
                        <svg xmlns="http://www.w3.org/2000/svg" width="9%" height="9%" fill="currentColor" class="bi bi-arrow-left-circle"
                            viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z" />
                        </svg>
                    </a>
                    <h2 class="text-center"><strong>Авторизация</strong></h2>
                </div>
                <div class="card px-5 py-3 d-flex align-items-center foodplan__shadow">
                    <form>
                        <h1 class="mb-4 text-center"><strong>Вход</strong></h1>
                        <div class="mb-3">
                            <label for="exampleInputEmail1" class="form-label">Email</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp">
                        </div>
                        <div class="mb-3">
                            <div class="d-flex align-items-center justify-content-between">
                                <label for="exampleInputPassword1" class="form-label">Пароль</label>
                                <small><a href="#" class="link-dark foodplan_green">Забыли пароль?</a></small>
                            </div>
                            <input type="password" class="form-control" id="password">
                        </div>
                        <div class="row mb-3">
                            <div class="col-12 col-sm-6 mt-3">
                                <button type="submit"
                                    class="btn w-100 btn-outline-success shadow-none foodplan_green foodplan__border_green">Войти</button>
                            </div>
                            <div class="col-12 col-sm-6 mt-3 d-flex justify-content-center align-items-center">
                                <small>Нет аккаунта? <a href="#" class="link-dark foodplan_green">Зарегистрируйтесь</a></small>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <nav class="navbar navbar-expand-md navbar-light mt-5">
            <div class="container p-2">
                <a class="navbar-brand" href="#">
                    <img src="img/logo.8d8f24edbb5f.svg" height="55" width="189" alt="">
                </a>
                <div class="footer__sideBtns d-flex">
                    <a href="#">
                        <img src="img/vk.png" height="38" width="auto" alt="">
                    </a>
                </div>
            </div>
        </nav>
    </footer>
    <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
        <div class="container d-flex flex-row justify-content-center mb-2">
            <small class="text-center">
                <h6>© Девман2022. Все права защищены. © Devman2022. All right reserved.</h6>
                <a href="#" class="link-secondary">Политика конфиденциальности</a>
            </small>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html >
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/faw_logo.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">
            <div class="container">

                  <a class="navbar-brand" href="{% url 'plan:home' %}">
                      <img src="{% static 'img/icon.svg' %}" height="70" width="160" alt="">
                  </a>
                  {% if request.user.is_authenticated %}
                      <a href="{% url 'plan:lk' %}" class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Подписки</a>
                      <a href="{% url 'plan:logout' %}" class="btn btn-outline-success shadow-none foodplan_green foodplan__border_green">Выйти</a>
                  {% else %}
                      <a href="{% url 'plan:login' %}" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">Войти</a>
                  {% endif %}
                  {% if request.get_full_path == "/order/" %}
                    <h3 class="text-secondary mt-2 me-2 myprice">Стоимость: 00000₽</h3>
                  {% endif %}
              </div>
          </nav>
      </header>
      {% block content %}
      {% endblock content %}
      {% block footer %}
      {% endblock footer %}

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
          crossorigin="anonymous"></script>
      <script type="text/javascript" src="http://code.jquery.com/jquery-2.2.4.min.js"></script>
      <script type="text/javascript" src="{% static 'js.js' %}"></script>
      <script type="text/javascript" src="{% static 'price.js' %}"></script>
  </body>
</html>

templates/card1.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню
{% endblock title %}

{% block content %}
  <main style="margin-top: calc(2rem + 75px);">
    <section>
      <div class="container">
        <div class="row">
          <div class="col-12 col-md-4 d-flex justify-content-center">
            <div class="card foodplan__card_borderless">
              <img src="{{ recipe.image.url }}" alt="">
            </div>
          </div>
          <div class="col-12 col-md-8 d-flex flex-column justify-content-between">
            <div class="row">
              <h2>{{ recipe.title }}</h2>
              <div class="col-12 col-sm-6 d-flex flex-column justify-content-between">
                <h6>{{ recipe.description }}</h6>
                <h6>{{ recipe.text }}</h6>
              </div>
              <div class="col-12 col-sm-6">
                <small class="link-secondary">Ингредиенты:</small>
                <ul class="list-group list-group-flush">
                  {% for item in ingredients %}
                    <li class="list-group-item disabled"><small>{{ item.ingredient.title }} ({{ item.quantity }}г.)</small></li>
                  {% endfor %}
                </ul>
                <small class="link-secondary">Общая калорийность: 1000 ккал</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
  {% include 'footer.html' %}
{% endblock content %}

templates/card2.html
{% extends 'base.html' %}
{% load static %}
{% block title %}План питания на неделю, меню, рецепты, список покупок. Классическое меню, безуглеводное меню{% endblock title %}

{% block content %}
    <main style="margin-top: calc(2rem + 75px);">
        <section>
            <div class="container">
                <div class="row">
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <img src="{{ recipe.image.url }}" alt="{% static 'img/circle1.png' %}">
                        </div>
                    </div>
                    <div class="col-12 col-md-6 d-flex flex-column justify-content-between">
                        <h2>{{ recipe.title }}</h2>
                        <ul class="list-group list-group-flush">
                            {% for item in ingredients %}
                              <li class="list-group-item">{{ item.ingredient.title }} ({{ item.quantity }}г.)</li>
                            {% endfor %}
                        </ul>
                        <h6>Общая калорийность: 1000 ккал</h6>
                    </div>
                <hr>
                    <div class="col-12 col-md-4 d-flex justify-content-center">
                        <div class="card foodplan__card_borderless">
                            <h5>Описание</h5>
                            <p>{{ recipe.description }}</p>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 d-flex flex-column justify-content-between">
                        <div class="card foodplan__card_borderless">
                            <h5>Рецепт</h5>
                            <p>{{ recipe.text }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% include 'footer.html' %}
{% endblock content %}

templates/footer.html
{% load static %}
<footer id="footer">
  <footer>
    <nav class="navbar navbar-expand-md navbar-light mt-5">
      <div class="container p-2">
        <a class="navbar-brand" href="#">
          <img src="{% static 'img/icon.svg' %}" height="70" width="160" alt="">
        </a>
        <div class="footer__sideBtns d-flex">
          <a href="#">
            <img src="{% static 'img/vk.png' %}" height="38" width="auto" alt="">
          </a>
        </div>
      </div>
    </nav>
  </footer>
  <footer class="footer pt-2" style="border-top: 1px solid lightgray;">
    <div class="container d-flex flex-row justify-content-center mb-2">
      <small class="text-center">
        <h6>© FoodPlan 2022. Все права защищены. © FoodPlan2022. All right reserved.</h6>
        <a href="https://vk.com/devmanorg" class="link-secondary">Политика конфиденциальности</a>
      </small>
    </div>
  </footer>
</footer>

templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Foodplan 2021 - Меню на неделю FOODPLAN{% endblock title %}

{% block content %}
<!--    <header>-->
<!--        <nav class="navbar navbar-expand-md navbar-light fixed-top navbar__opacity">-->
<!--            <div class="container">-->
<!--                <a class="navbar-brand" href="#">-->
<!--                    <img src="{% static 'img/logo.8d8f24edbb5f.svg' %}" height="55" width="189" alt="">-->
<!--                </a>-->
<!--                <h3 class="text-secondary mt-2 me-2 myprice">Стоимость: 00000₽</h3>-->
<!--                <button form="order" type="submit" class="btn shadow-none btn-sm btn-outline-success foodplan_green foodplan__border_green">Оплатить</button>-->
<!--            </div>-->
<!--        </nav>-->
<!--    </header>-->
    <main style="margin-top: calc(2rem + 85px);">
        <section>
            <div class="container">
                <h1><strong class="foodplan_green">1 шаг </strong>до первого меню</h1>
                <h5 class="text-secondary mb-3">Вам будет доступно 4 типа меню: Классическое, Низкоуглеводное, Вегетарианское и Кето.</h5>
                <div class="row mb-5">
                    <div class="col-6 col-md-3">
                        
                        <label for="classic" class="position-relative" style="cursor: pointer;">
                            <img src="{% static 'img/menu_classical.png' %}" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="classic" value="classic" class="foodplan_selected d-none">
                            <div class="img_selected" id="img1"></div>
                        </label>
                    </div>
                    <div class="col-6 col-md-3">
                        
                        <label for="low" class="position-relative" style="cursor: pointer;">
                            <img src="{% static 'img/menu_nizkougl.png' %}" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="low" value="low" class="foodplan_selected d-none">
                            <div class="img_selected" id="img2"></div>
                        </label>
                    </div>
                    <div class="col-6 col-md-3">
                        
                        <label for="veg" class="position-relative" style="cursor: pointer;">
                            <img src="{% static 'img/menu_veg.png' %}" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="veg" value="veg" class="foodplan_selected d-none">
                            <div class="img_selected" id="img3"></div>
                        </label>
                    </div>
                    <div class="col-6 col-md-3">
                        
                        <label for="keto" class="position-relative" style="cursor: pointer;">
                            <img src="{% static 'img/menu_keto.png' %}" alt="" class="w-100">
                            <input form="order" type="radio" name="foodtype" id="keto" value="keto" class="foodplan_selected d-none">
                            <div class="img_selected" id="img4"></div>
                        </label>
                    </div>
                </div>
                <h2><strong>Выберите подходящий тариф</strong></h2>
                <form id="order" method="POST">
                    {% csrf_token %}
                <table class="table text-center text-truncate mb-5">
                    <tbody>
                        <tr>
                            <th scope="row" class="text-start">Срок</th>
                            <td>
                                <select class="form-select" id="month" name="month">
                                    <option value="none" selected disabled hidden>Выберите срок подписки</option>
                                    <option value="0">1 мес.</option>
                                    <option value="1">3 мес.</option>
                                    <option value="2">6 мес.</option>
                                    <option value="3">12 мес.</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Завтраки</th>
                            <td>
                                <select name="select1" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Обеды</th>
                            <td>
                                <select name="select2" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Ужины</th>
                            <td>
                                <select name="select3" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Десерты</th>
                            <td>
                                <select name="select4" class="form-select">
                                    <option value="0" selected>&#10004;</option>
                                    <option value="1">&#10008;</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Кол-во персон</th>
                            <td>
                                <select name="select5" class="form-select">
                                    <option value="0" selected>1</option>
                                    <option value="1">2</option>
                                    <option value="2">3</option>
                                    <option value="3">4</option>
                                    <option value="4">5</option>
                                    <option value="5">6</option>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row" class="text-start">Аллергии</th>
                             <td>
                                {% for allergy in allergies %}
<!--                                <select name="{{ allergy.allergy_id }}" class="form-select">-->
                                    <div class="form-check d-flex justify-content-start">
                                        <input class="form-check-input me-1 foodplan_checked-green" type="checkbox" value="" name="allergy_{{allergy.id}}">
                                        <label class="form-check-label" for="allergy_{{allergy.id}}">
                                            {{ allergy.title }}
                                        </label>
                                    </div>
<!--                                </select>-->
                                {% endfor %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                <button type="submit" id="TableSubmit" class="d-none"></button>
                </form>

<!--        <form class="card d-flex flex-row align-items-baseline mb-5 p-3 foodplan__bg_grey">-->
<!--          <label for="promo_code" class="form-label me-2">Промокод</label>-->
<!--          <input type="password" class="form-control me-2" id="promo_code">-->
<!--          <button type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green">-->
<!--            Применить-->
<!--          </button>-->
<!--        </form>-->
<!--        <div class="d-flex justify-content-center my-5">-->
<!--          <a type="submit" href="{{ payment.confirmation.confirmation_url }}"-->
<!--             class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green w-50">Оплатить</a>-->
<!--        </div>-->
                <div class="d-flex justify-content-center my-5">
                    <button form="order" type="submit" class="btn shadow-none btn-outline-success foodplan_green foodplan__border_green w-50">Оплатить</button>
                </div>
      </div>
    </section>
  </main>
  {% include 'footer.html' %}
{% endblock content %}

templates/payment.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main>
	<div class="container mt-header">
        <article class="row position-relative">
            <div class="content-section mb-400">
                <div class="card card text-bg-secondary mb-6" style="width: 38rem;">
                  <h3 class="text-center">Оплата подписки "FoodPlan"</h3>
                  <form method="POST">
                      {% csrf_token %}
                    <div class="col-sm-8 mt-10">
                    <label class="col-sm-16 col-form-label">Сумма услуги ₽</label>
                    <input type="text" value="{{ results.PRICE }}" class="form-control bg-info">
                    <label class="col-sm-12 col-form-label">ЮMoney №</label>
                    <input type="text" name="receiver" value="4100117804701310" class="form-control bg-info" readonly>
                  </div>

                <h4 class="text-center"> О покупателе </h4>
                <div class="col-sm-8 mt-3">
                  <input type="text" class="form-control mb-4 bg-info" value="{{ results.NAME }}">
                  <input type="text" class="form-control mb-4 bg-info"  value="{{ results.PHONE}}" >
                  <input type="submit" value="Перевести {{ results.PRICE}} р " class="btn btn-info">
                </div>
                </form>
                <h6 class="mt-5"> Вы будете перенаправлены на защитный протокол для оплаты в Юkassa </h6>
                </div>
            </div>
        </article>
    </div>
</main>
    {% endblock content %}